title: Observatório Oceanográfico
description: Laboratório interdisciplinar da UFF dedicado às ciências do mar, mudanças climáticas e tecnologias ambientais
baseurl: ""
url: https://observatorio-oceanografico.github.io

collections:
  pages:
    output: true
  people:
    output: true
  projects:
    output: true
  resources:
    output: true
    permalink: /recursos/:name/   

defaults:
  - scope:
      path: ""
    values:
      layout: default

  - scope:
      type: projects
    values:
      layout: single

plugins:
  - jekyll-feed
  - jekyll-sitemap
